// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7G8WlPkIwu_XUVC_QMKsGVlj_TB5nxJY',
    appId: '1:616198733019:web:06fd69859fec9b801160fe',
    messagingSenderId: '616198733019',
    projectId: 'assignment-6-22dcf',
    authDomain: 'assignment-6-22dcf.firebaseapp.com',
    storageBucket: 'assignment-6-22dcf.appspot.com',
    measurementId: 'G-2542J9QEYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2eEutDhQ_PTxatQD__hUEtHeGzZaLw6o',
    appId: '1:616198733019:android:849beb824a24ccc61160fe',
    messagingSenderId: '616198733019',
    projectId: 'assignment-6-22dcf',
    storageBucket: 'assignment-6-22dcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9_xpL4mD-ahFs5Oy4JFizjYxICO8YROk',
    appId: '1:616198733019:ios:b9980c67a202dba41160fe',
    messagingSenderId: '616198733019',
    projectId: 'assignment-6-22dcf',
    storageBucket: 'assignment-6-22dcf.appspot.com',
    iosBundleId: 'com.example.assignment6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9_xpL4mD-ahFs5Oy4JFizjYxICO8YROk',
    appId: '1:616198733019:ios:f0593543d0982d9c1160fe',
    messagingSenderId: '616198733019',
    projectId: 'assignment-6-22dcf',
    storageBucket: 'assignment-6-22dcf.appspot.com',
    iosBundleId: 'com.example.assignment6.RunnerTests',
  );
}
